version: '3'

services:
    php:
        image: matthiasnoback/advanced_testing_workshop_devtools
        volumes:
            - ./:/opt:cached
            - ~/.composer:/home/.composer:cached
        environment:
            COMPOSER_HOME: /home/.composer
            XDEBUG_CONFIG: "remote_host=192.168.8.205"
            PHP_IDE_CONFIG: "serverName=php"
        user: 1000:1000
